{% set name = "sleap-io" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sleap_io-{{ version }}.tar.gz
  sha256: ae74b5c1913da7031ed53f678f9ab346c502c2d95b523f61a2da2f085b2478b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - ffmpeg
    - imageio
    - imageio-ffmpeg >=0.5.0
    - av
    - attrs
    - pandas
    - simplejson
    - h5py >=3.8.0
    - hdmf
    - numpy <2.0.0
    - opencv
    - pynwb
    - ndx-pose

test:
  imports:
    - sleap_io
  commands:
    - pip check
  requires:
    - pip
    # https://github.com/conda-forge/opencv-feedstock/issues/401#issuecomment-2028099423
    - libopencv *=headless*  # [linux]

about:
  summary: Standalone utilities for working with pose data from SLEAP and other tools.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/talmolab/sleap-io
  doc_url: https://io.sleap.ai

extra:
  recipe-maintainers:
    - talmo
